### ISSUE TITLE
Sentry

### ISSUE THREAD

**Issue by nandanrao** [zachweintraub/scum#7] opened 2021-08-29 21:45 UTC
As a player, I'm tired of hearing Zach ask me to look in the console for error messages. Let him read them himself.

**Comment by zachweintraub** [comment] 2021-08-29 21:47
Closing this as I cannot reproduce the issue.

**Closed as completed by zachweintraub** 2021-08-29 21:47 UTC

**Comment by nandanrao** [comment] 2021-08-29 22:02
https://sentry.io/welcome/
